---
credentials:
  - name: /concourse/((concourse_team))/((concourse_pipeline))/ops_manager_dns
    type: value
    value: ((ops_manager_dns))

  - name: /concourse/((concourse_team))/((concourse_pipeline))/opsman_password
    type: value
    value: ((opsman_password))

  - name: /concourse/((concourse_team))/((concourse_pipeline))/opsman_ssl
    type: value
    value: ((ssl_cert))

  - name: /concourse/((concourse_team))/((concourse_pipeline))/gcp_service_account_email
    type: value
    value: ((gcp_service_account_email))
