platform: linux

inputs:
- name: tas-srt-gcp-pipeline-repo

run:
  path: tas-srt-gcp-pipeline-repo/ci/tasks/load-tfvars-into-credhub/task.sh

params:
  CREDHUB_CA_CERT:
  CREDHUB_SECRET:
  CREDHUB_CLIENT:
  CREDHUB_SERVER:
