platform: linux

inputs:
- name: platform-automation-tasks
- name: tas-srt-gcp-pipeline-repo
- name: env

run:
  path: tas-srt-gcp-pipeline-repo/ci/tasks/apply-director-changes/task.sh

params:
  ENV_FILE: env.yml
  IGNORE_WARNINGS: "false"
  OM_VAR_management_subnet_name: ((management_subnet_name))
  OM_VAR_ops_manager_dns: ((ops_manager_dns))
  OM_VAR_ops_manager_public_ip: ((ops_manager_public_ip))
  OM_VAR_ops_manager_ssh_public_key: ((ops_manager_ssh_public_key))
  OM_VAR_ops_manager_tags: ((ops_manager_tags))
  OM_VAR_opsman_decryption_passphrase: ((opsman_decryption_passphrase))
  OM_VAR_opsman_password: ((opsman_password))
  OM_VAR_pivnet_token: ((pivnet_token))
  OM_VAR_region: ((region))
  OM_VARS_ENV: OM_VAR
