env: dev

concourse_team: main
concourse_pipeline: srt-pipeline
gcp_project_id: srt-test-4
project_name: srt-test-4
region: europe-west2
zone: europe-west2-b
folder_name: spikes
bucket_location: EU
parent_domain: engineerbetter.com
tas_version: 2.7.31
opsman_version: 2.7.29
tas_stemcell: "456.137"

tas_config_file: cf.yml
