az-configuration:
  - name: europe-west2-a
    iaas_configuration_name: default
  - name: europe-west2-b
    iaas_configuration_name: default
  - name: europe-west2-c
    iaas_configuration_name: default
iaas-configurations:
  - additional_cloud_properties: {}
    associated_service_account: ((env))-ops-manager@((gcp_project_id)).iam.gserviceaccount.com
    default_deployment_tag: pcf-vms
    name: default
    project: ((gcp_project_id))
network-assignment:
  network:
    name: ((env))-network
  other_availability_zones: []
  singleton_availability_zone:
    name: europe-west2-a
networks-configuration:
  icmp_checks_enabled: false
  networks:
    - name: ((env))-network
      subnets:
        - iaas_identifier: ((env))-network/((env))-management-subnet/europe-west2
          cidr: 10.0.0.0/26
          dns: 8.8.8.8,8.8.4.4
          gateway: 10.0.0.1
          reserved_ip_ranges: 10.0.0.3-10.0.0.10
          availability_zone_names:
            - europe-west2-a
            - europe-west2-b
            - europe-west2-c
        - iaas_identifier: ((env))-network/((env))-services-subnet/europe-west2
          cidr: 10.0.8.0/24
          dns: 8.8.8.8,8.8.4.4
          gateway: 10.0.8.1
          reserved_ip_ranges: 10.0.8.0-10.0.8.10
          availability_zone_names:
            - europe-west2-a
            - europe-west2-b
            - europe-west2-c
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.google.com
    post_deploy_enabled: false
    resurrector_enabled: false
    retry_bosh_deploys: false
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: false
    trusted_certificates: ((tls_issuer))
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    swap_as_percent_of_memory_size: automatic
  director:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
vmextensions-configuration: []
vmtypes-configuration: {}
