platform: linux

params:
  DIRECTOR_CONFIG_FILE: director.yml
  ENV_FILE: env.yml
  OM_VAR_management_subnet_name: ((management_subnet_name))
  OM_VAR_ops_manager_dns: ((ops_manager_dns))
  OM_VAR_ops_manager_public_ip: ((ops_manager_public_ip))
  OM_VAR_ops_manager_ssh_public_key: ((ops_manager_ssh_public_key))
  OM_VAR_ops_manager_tags: ((ops_manager_tags))
  OM_VAR_opsman_decryption_passphrase: ((opsman_decryption_passphrase))
  OM_VAR_opsman_password: ((opsman_password))
  OM_VAR_pivnet_token: ((pivnet_token))
  OM_VAR_region: ((region))
  OM_VARS_ENV: OM_VAR
  OPS_FILES: ""
  VARS_FILES: ""

inputs:
- name: tas-srt-gcp-pipeline-repo
- name: platform-automation-tasks
- name: config
- name: env
- name: vars
  optional: true
- name: secrets
  optional: true
- name: ops-files
  optional: true

run:
  path: tas-srt-gcp-pipeline-repo/ci/tasks/configure-director/task.sh
