platform: linux

inputs:
- name: tas-srt-gcp-pipeline-repo

outputs:
- name: tas-srt-gcp-pipeline-repo

params:
  GCP_CREDENTIALS_JSON:

run:
  path: tas-srt-gcp-pipeline-repo/ci/tasks/write-gcp-creds-to-file/task.sh
